before_install:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_ef748fe1608c_key -iv $encrypted_ef748fe1608c_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
deploy:
  provider: script
  script: ./deploy.sh
language: python
python: 2.7
script: echo Build passed
